### ISSUE TITLE
Make possible to send a custom EventId UUID

### ISSUE THREAD

**Issue by puffnfresh** [YoEight/eventstore#10]
It looks like newEvent [generates a random UUID](https://github.com/YoEight/eventstore/blob/7c22a1748b5cf67d705e19b3330e4373d2439a03/Database/EventStore/Internal/Types.hs#L202) for each event pushed. My events already have a UUID since they're coming from an external system. I would like to use that, to gain more useful idempotency.

**Comment by YoEight** [comment]
Related to #11

**Comment by YoEight** [comment]
See f110f3fa061cbc849b41f1ed17ce72233936d44a
