### ISSUE TITLE
Add API for stream metadata

### ISSUE THREAD

**Issue by puffnfresh** [YoEight/eventstore#12]
I would like to set the max count of a stream so that I can make something like a checkpoint stream.

Being able to manipulate a stream's max age and ACL would also be useful.

**Comment by YoEight** [comment]
I found out how to do it by looking at the C# client. I might be able to do it for this week.

**Comment by YoEight** [comment]
See https://github.com/YoEight/eventstore/pull/15

**Comment by YoEight** [comment]
It's available on Hackage too

**Comment by puffnfresh** [comment]
:fireworks:
