### ISSUE TITLE
Add support for Competing Consumers

### ISSUE THREAD

**Issue by puffnfresh** [YoEight/eventstore#14]
Seems like EventStore 3.0.2 got a useful feature called competing consumers, which feature persistent subscriptions:

http://docs.geteventstore.com/introduction/competing-consumers/

Here's the .NET API:

http://docs.geteventstore.com/dotnet-api/3.1.0-pre/competing-consumers/

**Comment by YoEight** [comment]
Actually, competing consumers are available from 3.1.0 which isn't available yet (release). I have some work on that front but EventStore from 3.0.2 to 3.0.4 keeps returning `NotHandled` response when playing with persistent subscriptions.

**Comment by puffnfresh** [comment]
@YoEight you are awesome :clap:

**Comment by YoEight** [comment]
Done #21
