### ISSUE TITLE
eventstore-0.7.2.0 does not compile

### ISSUE THREAD

**Issue by peti** [YoEight/eventstore#16]
Citing from http://hydra.cryp.to/build/854856/nixlog/1/raw:

~~~~~~~~~
Database/EventStore.hs:163:8:
    Could not find module ‘Database.EventStore.Internal.TimeSpan’
    Use -v to see a list of the files searched for.
~~~~~~~~~

**Comment by YoEight** [comment]
Thanks for pointing this. It appears I forgot to add that module in `eventstore.cabal`

**Comment by YoEight** [comment]
See 094fde3b11b2c3bf0c4a2453848bb59952480758

**Comment by YoEight** [comment]
I uploaded `0.7.2.1` version to hackage
