### ISSUE TITLE
Database.EventStore.connect: documentation typo

### ISSUE THREAD

**Issue by dnhgff** [YoEight/eventstore#23]
The documentation reads "Normally when you use a SQL connection you want to keep the connection open for a much longer of time than when you use a SQL connection."

I believe either the first or the second occurrence of "SQL connection" should be "Event Store connection", but it is not clear which it should be.

**Comment by YoEight** [comment]
You're right, the first occurrence should be 'EventStore connection'. I'll fix that. Thanks for pointing this.

**Comment by YoEight** [comment]
Done https://github.com/YoEight/eventstore/commit/d523b019500875bbda3238b3575524f386876fb0
