### ISSUE TITLE
eventstore-0.8.0.0 does not compile

### ISSUE THREAD

**Issue by peti** [YoEight/eventstore#27]
Citing from http://hydra.nixos.org/build/25135256/log/raw:

~~~~
Database/EventStore/Internal/Types.hs:445:56:
    Couldn't match type ‘Int64’ with ‘Int32’
    Expected type: Int64 -> CTime
      Actual type: Int32 -> CTime
    In the second argument of ‘(.)’, namely ‘CTime’
    In the second argument of ‘(.)’, namely ‘realToFrac . CTime’
~~~~~

That code seems to assume it's running on a 64 bit machine?

**Comment by YoEight** [comment]
Hello @peti, thanks for reporting this.

Indeed, and I should have mention it, it only runs on 64bits machine. Note that isn't a restriction of mine but rather something needed by the EventStore protocol. `Int64` is used for commit position for instance.
