### ISSUE TITLE
readEvent fails on Slave nodes

### ISSUE THREAD

**Issue by bobthemighty** [YoEight/eventstore#50]
When using readEvent to fetch event 0 from a stream, we receive an error if connecting to a slave node.

```
*Main Lib Process> connect defaultSettings "10.128.204.191" 1113 >>= \conn -> readEvent conn "batches" 0 False >>= wait

*** Exception: InvalidServerResponse 177 241
```

```
*Main Lib Process> connect defaultSettings "10.128.236.46" 1113 >>= \conn -> readEvent conn "batches" 0 False >>= wait

ReadSuccess ReadEvent {readEventStream = "batches", readEventNumber = 0, readEventResolved = ResolvedEvent {resolvedEventRecord = Just (RecordedEvent {recordedEventStreamId = "batches", recordedEventId = 2ad56c57-b601-1143-8c50-ce46d51880df, recordedEventNumber = 0, recordedEventType = "batch_quantity_changed", recordedEventData = "{\n  \"batch_id\": \"689434f3-c772-49e9-9229-5ca891172f02\",\n  \"product_sku\": \"CHARTC024GRY-UK\",\n  \"unallocated_quantity\": 1\n}", recordedEventMetadata = Just "", recordedEventIsJson = True, recordedEventCreated = Just 2015-06-17 20:08:08.12 UTC}), resolvedEventLink = Nothing, resolvedEventPosition = Nothing}}
```

```
*Main Lib Process> connect defaultSettings "10.128.212.175" 1113 >>= \conn -> readEvent conn "batches" 0 False >>= wait
*** Exception: InvalidServerResponse 177 241
```

**Comment by YoEight** [comment]
Thanks to report this issue.

I need more details though. Could you provide which library and server versions you're using.

**Comment by YoEight** [comment]
If possible too, could you provide a contrived code snippet triggering the issue. It can really speed up the resolution process.

Thanks

**Comment by YoEight** [comment]
Unless you don't do much comparing to your given ghci session above

**Comment by YoEight** [comment]
Also, it sounds you're in a cluster settings yet you don't use cluster based settings

**Comment by bobthemighty** [comment]
Aha! Cluster-connection settings sounds about right. I thought I had read that the client would find nodes from a seed. Let me catch up with the developer who reported the issue, @damiansoriano , and get back to you, but this is probably our fault.

**Comment by YoEight** [comment]
No problem ! Don't hesitate to ask if you need help to use cluster connection settings.

**Comment by damiansoriano** [comment]
@YoEight Cluster connection fix that issue, thanks for that. Closing this non-issue
