### ISSUE TITLE
eventstore-0.12.0.0  (LTS-6.x) does not compile on 32 bit Linux

### ISSUE THREAD

**Issue by peti** [YoEight/eventstore#51]
Citing from https://build.opensuse.org/package/live_build_log/devel:languages:haskell:lts:6/ghc-eventstore/openSUSE_Tumbleweed/i586:

~~~~
[  161s] Database/EventStore/Internal/Types.hs:343:56:
[  161s]     Couldn't match type ‘Int64’ with ‘Int32’
[  161s]     Expected type: Int64 -> CTime
[  161s]       Actual type: Int32 -> CTime
[  161s]     In the second argument of ‘(.)’, namely ‘CTime’
[  161s]     In the second argument of ‘(.)’, namely ‘realToFrac . CTime’
~~~~

**Comment by YoEight** [comment]
Thanks to report this but EventStore server expects 64bits integer in many places thus doesn't support 32bits systems.

**Comment by peti** [comment]
Well, if this is a conscious decision, then it would be really great of
the documentation and the build instructions clearly reflected that fact
so that people trying to compile this package on other platforms don't
waste their time.

**Comment by YoEight** [comment]
Thanks sir and have a nice day
