### ISSUE TITLE
thread blocked indefinitely in an STM transaction during reconnection

### ISSUE THREAD

**Issue by Akii** [YoEight/eventstore#61]
Using this program:

```haskell
{-# LANGUAGE OverloadedStrings #-}

module Test4 where

import Database.EventStore
import Control.Monad (forever)

main :: IO ()
main = do
  es <- connect defaultSettings { s_retry = keepRetrying } (Static "localhost" 1113)
  sub <- subscribeFrom es "strim" True (Just 15) (Just 500)

  forever $ do
    next <- resolvedEventOriginal <$> nextEvent sub
    print $ recordedEventNumber next
```

The driver will recover from killing the eventstore once. On the second kill, the exception is thrown.

```
15
16
17
16 -- after the first kill
17
*** Exception: thread blocked indefinitely in an STM transaction -- after the second kill
```

It's also weird that the driver sends the last 2 events. This is described in more detail in an upcoming issue.

Expected behaviour: The driver should just continue to reconnect in the background and no exception should be thrown.

**Comment by YoEight** [comment]
Thanks for the detailed report, I will look at this on the weekend

**Comment by Akii** [comment]
This is the smallest example code that demonstrates the issue. You can see how the eventstore will print `External TCP connection accepted` for two restarts. Without creating the subscription the driver will try to connect forever as intended.

This will cause the driver to stop connecting after 2 disconnects:
```
es <- connect defaultSettings { s_retry = keepRetrying } (Static "localhost" 1113)
sub <- subscribeFrom es "strim" True (Just 18) (Just 500)
_ <- getLine
```

With this the driver will re-connect forever:
```
es <- connect defaultSettings { s_retry = keepRetrying } (Static "localhost" 1113)
_ <- getLine
```

**Comment by YoEight** [comment]
Bug confirmed

**Comment by YoEight** [comment]
Fixed
