### ISSUE TITLE
Driver re-sends already processed events in catchup subscriptions

### ISSUE THREAD

**Issue by Akii** [YoEight/eventstore#62]
In #61 the last 2 events are resent after killing the store. I thought that was pretty odd and thought it's an off-by-2 problem.

Turns out if you start a catchup-subscription with an event number higher than the max event number of the stream all events are resent after reconnecting to the store.

Given a stream that contains 18 events, called "strim":

`sub <- subscribeFrom es "strim" True (Just 14) (Just 500)`

Running the subscription with following program:

```
  forever $ do
    next <- resolvedEventOriginal <$> nextEvent sub
    print $ recordedEventNumber next
```

Will result in the output:

```
14
15
16
17
```

as expected. After eventstore reconnection the output will look like this:

```
14
15
16
17
16
17
```

I would expect the output to not change.

Starting the subscription at the current event:

`sub <- subscribeFrom es "strim" True (Just 18) (Just 500)`

will produce following output:

```
```

as expected (no events processed). But will result in

```
0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
```

after a eventstore reconnection occurs.
Expected behaviour here would be unchanged output.

**Comment by YoEight** [comment]
Fixed

**Comment by Akii** [comment]
Thank you!
