### ISSUE TITLE
Recovering subscriptions from a connection loss fails

### ISSUE THREAD

**Issue by Akii** [YoEight/eventstore#65]
The basic use-case I have is that I provide a WebSocket where I send events to the browser. For this I use a volatile subscription (although I've also confirmed this for catchup-subs).

My recovery strategy is to simply re-sub to a stream after the exception `SubscriptionClosed` is thrown. With #61 fixed this should be possible.

To reproduce this bug the following setup is needed:
* running store at localhost:1113
* existing stream named "strim"
* a way to send an event to that stream

Code for testing:

```haskell
{-# LANGUAGE ScopedTypeVariables #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE NoImplicitPrelude #-}

module Test where

import ClassyPrelude
import Database.EventStore
import Control.Concurrent (forkIO)

main :: IO ()
main = do
  con <- connect defaultSettings { s_retry = keepRetrying } (Static "localhost" 1113)

  _ <- void . forkIO . forever $ handle (\(_ :: SubscriptionClosed) -> threadDelay 5000000) (mkSub con >>= process)

  -- this will make it so we can run our tests
  _ <- getLine :: IO String

  shutdown con >> waitTillClosed con

  where
    mkSub c = do
      putStrLn "making a subscription"
      sub <- subscribe c "strim" True

      waitConfirmation sub
      putStrLn "sub confirmed"

      return sub

    process sub = do
      putStrLn "processing..."

      forever $ do
        n <- nextEvent sub
        print (recordedEventNumber $ resolvedEventOriginal n)
```

To execute the test, do the following:
* start up the store
* run the script and send an event to that stream to confirm it's working

```
making a subscription
sub confirmed
processing...
81729
81730
```

* next, kill the store. The driver will abort the subscription and the test script will try creating a new subscription. Output is:

```
making a subscription
sub confirmed
processing...
81729
81730
making a subscription
```

* bring the store back up. Nothing else will happen.

Expected output would be a confirmed subscription and a continuation of processing:

```
making a subscription
sub confirmed
processing...
81729
81730
making a subscription
sub confirmed
processing...
81731
```

By inserting a `threadDelay 5000000` in the exception handling function the driver seems to be able to recover, however this is unreliable at best.

**Comment by YoEight** [comment]
As for now, I unable to reproduce it.
