### ISSUE TITLE
Feedback : Making calls safe or document errors that could occur

### ISSUE THREAD

**Issue by nhenin** [YoEight/eventstore#98]
Hi I'm using your client in my application, and I'm now dealing with handling Errors...
It could be cool  if you provide what kind of exceptions that could raise from the different calls (but this documentation could be not up to date...) or even provide a safe version of your API with something like `Either CallErros a`

I'm trying to figure out for example what kind of errors you are triggering for readEventsForward by example...

P.S : thank you for the lib otherwise... I can use the eventstore thanks to you...

**Comment by YoEight** [comment]
Hi there!

You probably did see it but, the repository moved last year to https://gitlab.com/YoEight/eventstore-hs.

Also for direct communication, I also set up a discord server, where I advise you to post your question: https://discord.gg/x7q37jJ

I'm closing that ticket and expect to see you at the other venues.
